### ISSUE TITLE
Deserialization Range Options

### ISSUE THREAD

**Issue by Meorawr** [rossnichols/LibSerialize#6]
This is a small feature idea to add some options to the deserialization process via an optional `options` table parameter on the following functions:

```lua
function LibSerialize:DeserializeValue(input[, options])
function LibSerialize:Deserialize(input[, options])
```

The options table if given would support the following fields, all optional.

```lua
options = {
    inputPos = 20,
    inputLen = 20,
}
```

**inputPos**
This would be the position to start at in the `input` string, defaulting to `1` if not given.

**inputLen**
This would represent the number of bytes in the `input` string to process, defaulting to `#input` if not given.

The use case for these fields is primarily to allow LibSerialize to more efficiently work on a smaller range of an input string without requiring a potentially expensive substring/alloc operation.

An example could be when dealing with incoming data that has prefixed some data external to the payload, such as versioning or processing instructions for the remainder of the input. In the current world you'd need to read such a header and then do a substring on a potentially large segment of the payload to carve out the precise section that you'd want processing by LibSerialize.

As LibSerialize already has the Reader concept with these two variables already hanging around, so it _should_ just be case of passing the offset/count from the outer Deserialize functions through the CreateDeserializer/CreateReader calls:

https://github.com/rossnichols/LibSerialize/blob/5a1cbe3d7df11ac432252f05d0ac9239d87fdbbc/LibSerialize.lua#L490-L492

**Comment by rossnichols** [comment]
Just to make sure I understand the idea correctly, it's that you have some large string of which a subset is a LibSerialize'd string, and you want to give LibSerialize the entire string and tell it "the part you're interested in is \<here\>", rather than having to split it out first?

**Comment by Meorawr** [comment]
Yeah, as an example:

```lua
local input = "Serializer:LibSerialize;Payload:binarydatagoesherethatneedsprocessingbylibserialize;TrailingExposition:true"
local value = LibSerialize:Deserialize(input, { inputPos = 33, inputLen = 51 });
```

Internally the above example would cause LibSerialize to just bound its reader to byte offset 33 and read up-to a maximum of 51 bytes, thus operating only on the `binarydatagoesherethatneedsprocessingbylibserialize` section of that input string.

**Comment by rossnichols** [comment]
Yeah that makes sense, and shouldn't be too hard to implement as you mentioned. There will probably be more error handling and tests than actual code :).

Are you interested in implementing it yourself, or are you fine waiting until I do it? How urgently is the feature needed? Not super urgently I assume, since it's more of a performance optimization than new functionality.

**Comment by Meorawr** [comment]
I'd be fine with waiting - it's not urgent. I might take a look at implementing it eventually but I'll ping you first if I get to that point.

**Comment by SafeteeWoW** [comment]
I think it should be a part of the "input" parameter, because this completely changes the input, for example

input = {
  str = "Serializer:LibSerialize;Payload:binarydatagoesherethatneedspro",
  inputPos = 20,
  inputLen = 20,
}

**Comment by rossnichols** [comment]
It doesn't completely change the input, it's just adding a pair of directives to say which part of the input should be used. I'd prefer to have a consistent `(inputString, optionsTable)` parameter set rather than have a more complex API shape.

**Comment by Meorawr** [comment]
I'd say you're not really completely changing the input as much as you are just configuring how it's read.

The idea of having it in an options table is mostly for future extensibility; I had some other options in mind at some point such as providing an explicit version to Deserialize and having it not read the initial byte, though my use case for that _may_ have faded slightly and I didn't want to overload a single request with four extremely specialized options.

If I were to pass a table into the Deserialize function as its input parameter then I wouldn't be expecting it to define a slice of a string in the same way that you don't pass tables into any of Lua's APIs to control the operated-upon range - instead they expect optional `i` and `j` parameters where such things are supported. Rather, if I passed a table into the Deserialize function then my initial expectation would be one of two things - either it'd process the given table as an array of bytes, or it'd treat it as a custom Reader-like struct with functions for reading data (which, incidentally, is something I'd quite like).

**Comment by rossnichols** [comment]
Now that generic reader support is in, this should be supported. Not sure if we need to add "first class" support for it via built-in options.
